INSERT INTO Car
(ID, BRAND, MODAL, YEAR_MAKE,PRICE, STATUS)
VALUES(1, 'Mazda', 'Mazda 3', 2000, 200000,'Available');

INSERT INTO Car
(ID, BRAND, MODAL, YEAR_MAKE,PRICE, STATUS)
VALUES(2, 'Mazda', 'Mazda 6', 2000, 200000,'Sold');

INSERT INTO Car
(ID, BRAND, MODAL, YEAR_MAKE,PRICE, STATUS)
VALUES(3, 'Toyota', 'Corolla', 2000, 200000,'Available');

INSERT INTO Car
(ID, BRAND, MODAL, YEAR_MAKE,PRICE, STATUS)
VALUES(4, 'Toyota', 'Avalon', 2000, 200000,'Sold');